name = "Ape Escape 3"
home = "https://discord.com/channels/731205301247803413/1336332485788831825"
default_url = "https://github.com/aidanii24/ae3-archipelago/releases/download/v{{version}}/ape_escape_3.apworld"

[versions]
"1.0.60" = {}
"1.0.70" = {}
"1.0.71" = {}
"1.0.80-exp" = { url = "https://github.com/aidanii24/ae3-archipelago/releases/download/v1.0.80exp/ape_escape_3.apworld" }
"2.0.0" = {url = "https://github.com/aidanii24/ae3-archipelago/releases/download/v2.0.00-beta.3%2B1/ape_escape_3.apworld"}
