name = "Astalon"
home = "https://discord.com/channels/731205301247803413/1211521722881286164"
default_url = "https://github.com/drtchops/Archipelago-Astalon/releases/download/v{{version}}/astalon.apworld"

[versions]
"0.17.0" = {}
"0.18.2" = {}
"0.21.2" = {}
"0.23.1" = {}
"0.24.0-rc3" = {}
"0.24.0" = {}
"0.24.1" = {}
"0.25.0" = {}
