name = "Brave Fencer Musashi"
home = "https://discord.com/channels/731205301247803413/1291453297370337351"
default_url = "https://github.com/AegeusEvander/Brave-Fencer-Musashi-AP-World/releases/download/v{{version}}/bfm.apworld"

[versions]
"0.2.1" = {}
"0.2.4" = {}
