name = "DeathLinkipelago"
home = "https://discord.com/channels/731205301247803413/1358292614386024538"
default_url = "https://github.com/SWCreeperKing/DeathLinkipelago/releases/download/v.{{version}}hf/deathlinkipelago.apworld"

[versions]
"0.11.3" = {}
