name = "EarthBound"
home = "https://discord.com/channels/731205301247803413/1077266688657068032"

[versions]
"3.2.0" = { url = "https://github.com/PinkSwitch/Archipelago/releases/download/earthboundap3.2/earthbound.apworld" }
"3.3.1" = { url = "https://github.com/PinkSwitch/Archipelago/releases/download/earthboundap3.3.1/earthbound.apworld" }
"3.5.0" = { url = "https://github.com/PinkSwitch/Archipelago/releases/download/earthboundap3.5/earthbound.apworld" }
"4.0.0" = { url = "https://github.com/PinkSwitch/Archipelago/releases/download/earthboundap4.0/earthbound.apworld" }
