name = "Frogmonster"
home = "https://discord.com/channels/731205301247803413/1271323478779363398"
default_url = "https://github.com/Rooby-Roo/FrogmonsterAPWorld/releases/download/v{{version}}/frogmonster.apworld"

[versions]
"0.1.0" = {}