name = "Gauntlet Legends"
home = "https://discord.com/channels/731205301247803413/1195336830258778183"
default_url = "https://github.com/jamesbrq/GauntletLegendsAP/releases/download/v{{version}}/gl.apworld"

[versions]
"1.7.1" = {}
"1.7.2" = {}
