name = "Grim Dawn"
home = "https://discord.com/channels/731205301247803413/1114646643225137224"
default_url = "https://github.com/routhken/Archipelago/releases/download/v{{version}}/grim_dawn.apworld"

[versions]
"0.1.5" = { url = "https://github.com/routhken/Archipelago/releases/download/grimdawn-v0.1.5/grim_dawn.apworld" }
"0.2.0" = {}
"0.3.0" = {}

