name = "Manual_TheGrinchPS1_MarioSpore"
display_name = "Manual: The Grinch (PS1)"
home = "https://discord.com/channels/1097532591650910289/1241790605508608029"
default_url = "https://github.com/MarioSpore/manual_thegrinchps1_mariospore/releases/download/v{{version}}/manual_thegrinchps1_mariospore.apworld"

[versions]
"1.0.0" = { url = "https://github.com/MarioSpore/manual_thegrinchps1_mariospore/releases/download/v1.0/manual_thegrinchps1_mariospore.apworld" }
"1.0.2" = {}
"1.1.0" = {}
"1.1.2" = {}
