name = "manual_mariovsdonkeykong_rampantepsilon
display_name = "Manual: Mario VS Donkey Kong"

[versions]
"1.2.0" = { url = "https://github.com/rampantepsilon/Manual_MarioVSDonkeyKong_RampantEpsilon/releases/download/1.2.0/manual_mariovsdonkeykong_rampantepsilon.apworld" }
