name = "Mario Kart Double Dash"
home = "https://discord.com/channels/731205301247803413/1257102472967884882"
default_url = "https://github.com/aXu-AP/archipelago-double-dash/releases/download/v{{version}}/mario_kart_double_dash.apworld"

[versions]
"0.1.1" = {}
"0.1.1+fantanoice1" = { url = "https://github.com/fantanoice/archipelago-double-dash/releases/download/v0.1.1+fantanoice1/mario_kart_double_dash.apworld" }
"0.2.1" = {}
"0.2.2" = {}
