name = "Placid Plastic Duck Simulator"
home = "https://discord.com/channels/731205301247803413/1104785671262056559"
default_url = "https://github.com/SWCreeperKing/PPDSArchipelago/releases/download/v.{{version}}/placidplasticducksim.apworld"

[versions]
"0.1.1-hf1" = {}
"0.1.1" = {}
"0.1.2" = {url = "https://github.com/SWCreeperKing/PPDSArchipelago/releases/download/v0.1.2/placidplasticducksim.apworld"}
