name = "Pokemon Crystal"
home = "https://discord.com/channels/731205301247803413/1365127145709502575"
default_url = "https://github.com/gerbiljames/Archipelago/releases/download/{{version}}/pokemon_crystal.apworld"

[versions]
"4.0.12" = {}
"5.0.0" = {}
"5.0.1" = {}
"5.0.2" = {}
"5.0.3" = {}
"5.1.0" = {}
"5.1.1" = {}
"5.1.2" = {}
"5.1.3" = {}
"5.1.4" = {}
"5.1.5" = {}
"5.1.6" = {}
"5.2.2" = {}
"5.2.4" = {}
"5.2.5" = {}
