name = "Pokemon Crystal"
home = "https://discord.com/channels/731205301247803413/1365127145709502575"
default_url = "https://github.com/gerbiljames/Archipelago/releases/download/{{version}}/pokemon_crystal.apworld"

[versions]
"2.1.2" = {}
"3.0.0" = {}
"3.0.1" = {}
"3.1.0" = {}
"3.1.2" = {}
"3.1.3" = {}
"3.2.0" = {}
"3.2.1" = {}
"3.2.2" = {}
"3.2.3" = {}
"3.2.4" = {}
"4.0.0" = {}
"4.0.1" = {}
"4.0.2" = {}
