name = "Powerwash Simulator"
home = "https://discord.com/channels/731205301247803413/1158367507703410739"
default_url = "https://github.com/SWCreeperKing/PowerwashSimAP/releases/download/v.{{version}}/powerwashsimulator.apworld"

[versions]
"0.1.0+hf3" = { url = "https://github.com/SWCreeperKing/PowerwashSimAP/releases/download/v.0.1-hf3/powerwashsimulator.apworld" }
"0.3.2" = {}
"0.5.1" = {}
"0.5.2" = {}
"0.5.3" = {}
"0.5.5" = {}
"0.5.12" = {url = "https://github.com/SWCreeperKing/PowerwashSimAP/releases/download/v0.5.12/powerwashsimulator.apworld"}
