name = "Satisfactory"
home = "https://discord.com/channels/731205301247803413/1018853131859267656"
default_url = "https://github.com/Jarno458/SatisfactoryArchipelagoMod/releases/download/world-v{{version}}/satisfactory.apworld"

[versions]
"2.2.0" = {}
