name = "The Minish Cap"
home = "https://discord.com/channels/731205301247803413/1091489558325112873"
default_url = "https://github.com/eternalcode0/Archipelago/releases/download/v{{version}}/tmc.apworld"

[versions]
"0.0.10" = {}
"0.1.0-rc2" = {}
"0.1.0" = {}
"0.2.0" = {}
