name = "Paper Mario: The Thousand-Year Door"
home = "https://discord.com/channels/731205301247803413/1205136944259145728"
default_url = "https://github.com/jamesbrq/ArchipelagoTTYD/releases/download/v{{version}}/ttyd.apworld"

[versions]
"0.5.3-HOTFIX" = {}
"0.6.2" = {}
