[["test.general.test_items.TestBase.test_item_name_group_has_valid_item [Weapons] (group_name='Weapons', game_name='Iji')"]]
__expected__ = "fail"
__version__ = ">=1.1.3"

[["test.general.test_items.TestBase.test_item_name_group_has_valid_item [Normal Weapons] (group_name='Normal Weapons', game_name='Iji')"]]
__expected__ = "fail"
__version__ = ">=1.1.3"

[["test.general.test_items.TestBase.test_item_name_group_has_valid_item [Special Weapons] (group_name='Special Weapons', game_name='Iji')"]]
__expected__ = "fail"
__version__ = ">=1.1.3"

[["test.general.test_reachability.TestBase.test_default_all_state_can_reach_everything [Region should be reached] (region='Sector Z Inner Prey', game='Iji')"]]
__expected__ = "fail"
__version__ = ">=1.1.3"

[["test.general.test_reachability.TestBase.test_default_all_state_can_reach_everything [Region should be reached] (region='Sector Y', game='Iji')"]]
__expected__ = "fail"
__version__ = ">=1.1.3"
