[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='generate_basic', game='Manual_RhythmDoctor_crimsonDestroyer')"]]
__expected__ = "fail"
__version__ = ">=0.0.1"

[["test.general.test_items.TestBase.test_itempool_not_modified [step] (step='pre_fill', game='Manual_RhythmDoctor_crimsonDestroyer')"]]
__expected__ = "fail"
__version__ = ">=0.0.1"
